# Generated by Django 3.1.1 on 2020-09-15 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'TODO 목록', 'verbose_name_plural': 'TODO 목록'},
        ),
        migrations.AddField(
            model_name='todolist',
            name='is_progressed',
            field=models.BooleanField(default=False, verbose_name='진행여부'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='완료여부'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=30, verbose_name='타이틀'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저명'),
        ),
    ]
